//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicaciones
    {
        public Ubicaciones()
        {
            this.Alojamientos = new HashSet<Alojamientos>();
        }
    
        public int idUbicacion { get; set; }
        public string nombreCiudad { get; set; }
        public string nombreDepartamento { get; set; }
        public string direccion { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Alojamientos> Alojamientos { get; set; }
    }
}
