//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arrendatarios
    {
        public Arrendatarios()
        {
            this.CalificacionesAlojamiento = new HashSet<CalificacionesAlojamiento>();
            this.CalificacionesArrendatario = new HashSet<CalificacionesArrendatario>();
        }
    
        public int idArrendatario { get; set; }
        public string tipoArrendador { get; set; }
        public string cedulaArrendatario { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<CalificacionesAlojamiento> CalificacionesAlojamiento { get; set; }
        public virtual ICollection<CalificacionesArrendatario> CalificacionesArrendatario { get; set; }
    }
}
