//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arrendadores
    {
        public Arrendadores()
        {
            this.Alojamientos = new HashSet<Alojamientos>();
            this.CalificacionesArrendatario = new HashSet<CalificacionesArrendatario>();
        }
    
        public int idArrendador { get; set; }
        public string cedula { get; set; }
    
        public virtual ICollection<Alojamientos> Alojamientos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<CalificacionesArrendatario> CalificacionesArrendatario { get; set; }
    }
}
