//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalificacionesAlojamiento
    {
        public int idCalificacion { get; set; }
        public string cedulaArrendatario { get; set; }
        public int idAlojamiento { get; set; }
        public System.DateTime fechaCalificacion { get; set; }
    
        public virtual Alojamientos Alojamientos { get; set; }
        public virtual Arrendatarios Arrendatarios { get; set; }
        public virtual Calificaciones Calificaciones { get; set; }
    }
}
