//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalificacionesArrendatario
    {
        public int idCalificacion { get; set; }
        public string cedulaArrendatario { get; set; }
        public string cedulaArrendador { get; set; }
        public System.DateTime fechaCalificacion { get; set; }
    
        public virtual Arrendadores Arrendadores { get; set; }
        public virtual Arrendatarios Arrendatarios { get; set; }
        public virtual Calificaciones Calificaciones { get; set; }
    }
}
