//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RoomServicesEntities : DbContext
    {
        public RoomServicesEntities()
            : base("name=RoomServicesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Administradores> Administradores { get; set; }
        public DbSet<AlbumFotograficos> AlbumFotograficos { get; set; }
        public DbSet<Alojamientos> Alojamientos { get; set; }
        public DbSet<AlquilersAlojamientos> AlquilersAlojamientos { get; set; }
        public DbSet<Arrendadores> Arrendadores { get; set; }
        public DbSet<Arrendatarios> Arrendatarios { get; set; }
        public DbSet<Calificaciones> Calificaciones { get; set; }
        public DbSet<CalificacionesAlojamiento> CalificacionesAlojamiento { get; set; }
        public DbSet<CalificacionesArrendatario> CalificacionesArrendatario { get; set; }
        public DbSet<CuentasBancarias> CuentasBancarias { get; set; }
        public DbSet<CuentasUsuarios> CuentasUsuarios { get; set; }
        public DbSet<Ubicaciones> Ubicaciones { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    }
}
