//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Alojamientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alojamientos()
        {
            this.AlbumFotograficos = new HashSet<AlbumFotograficos>();
            this.AlquilersAlojamientos = new HashSet<AlquilersAlojamientos>();
            this.CalificacionesAlojamiento = new HashSet<CalificacionesAlojamiento>();
        }
        [Key]
        public int idAlojamiento { get; set; }
        public string titulo { get; set; }
        public string descripcionAlojamiento { get; set; }
        public decimal precio { get; set; }
        public string tipoAlojamiento { get; set; }
        public int idUbicacion { get; set; }
        public string cedulaArrendador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlbumFotograficos> AlbumFotograficos { get; set; }
        public virtual Arrendadores Arrendadores { get; set; }
        public virtual Ubicaciones Ubicaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlquilersAlojamientos> AlquilersAlojamientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalificacionesAlojamiento> CalificacionesAlojamiento { get; set; }
    }
}
