//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AlquilersAlojamientos
    {
        [Key]
        public int numeroContrato { get; set; }
        public int numeroMeses { get; set; }
        public decimal pagoMensual { get; set; }
        public string fechaAlquiler { get; set; }
        public int idAlojamiento { get; set; }
    
        public virtual Alojamientos Alojamientos { get; set; }
    }
}
