//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CuentasUsuarios
    {
        [Key]
        public string email { get; set; }
        public string contrasena { get; set; }
        public string cedulaUsuario { get; set; }
    
        public virtual Administradores Administradores { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
