//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CuentasBancarias
    {
        [Key]
        public int numeroCuenta { get; set; }
        public decimal saldoCuenta { get; set; }
        public string cedula { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
