//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RoomServicesEntities1 : DbContext
    {
        public RoomServicesEntities1()
            : base("RoomServicesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
           // throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administradores> Administradores { get; set; }
        public virtual DbSet<AlbumFotograficos> AlbumFotograficos { get; set; }
        public virtual DbSet<Alojamientos> Alojamientos { get; set; }
        public virtual DbSet<AlquilersAlojamientos> AlquilersAlojamientos { get; set; }
        public virtual DbSet<Arrendadores> Arrendadores { get; set; }
        public virtual DbSet<Arrendatarios> Arrendatarios { get; set; }
        public virtual DbSet<Calificaciones> Calificaciones { get; set; }
        public virtual DbSet<CalificacionesAlojamiento> CalificacionesAlojamiento { get; set; }
        public virtual DbSet<CalificacionesArrendatario> CalificacionesArrendatario { get; set; }
        public virtual DbSet<CuentasBancarias> CuentasBancarias { get; set; }
        public virtual DbSet<CuentasUsuarios> CuentasUsuarios { get; set; }
        public virtual DbSet<Ubicaciones> Ubicaciones { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
